name: Send Birthday Emails

on:
  schedule:
    - cron: '0 17 * * *'  # Mỗi ngày lúc 0h (giờ Việt Nam = UTC+7)
  workflow_dispatch:       # Cho phép chạy thủ công để test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Quan trọng! Sửa lỗi bạn gặp

      - name: Compile Java code
        run: javac -cp src src/birthday/BirthdayMain.java

      - name: Run Java app
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: java -cp src birthday.BirthdayMain