name: Send Birthday Emails

on:
  schedule:
    - cron: '0 17 * * *'  # 0h mỗi ngày giờ Việt Nam (UTC+7)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Bắt buộc!

      - name: Compile Java code
        run: javac -cp src src/birthday/BirthdayMain.java

      - name: Run Java app
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: java -cp src birthday.BirthdayMain
