name: Send Birthday Emails

on:
  schedule:
    - cron: '0 17 * * *'  # 0h mỗi ngày giờ Việt Nam (UTC+7)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java code
        run: javac -cp "library/*:src/main/java" src/main/java/autoEmail/*.java src/main/java/database/*.java
  
      - name: Run Java app
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

        run: java -cp "library/*:src/main/java" autoEmail.MainEmail
        
